server:
  port: 9090
spring:
  datasource:
    url: jdbc:postgresql://localhost:54320/security
    username: postgres
    password: 30111997
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
